default_stages: [commit]
fail_fast: false
exclude: |
    (?x)(
      {{cookiecutter.repo_name}}/|
      test/example-project/
    )
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            exclude: mkdocs.yaml
          - id: check-ast
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: mixed-line-ending

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.3
      hooks:
          - id: prettier
            args: [--print-width=88, --tab-width=4]
            exclude: |
                (?x)(
                  .github/semantic_release/release_notes.hbs
                )
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.11.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]

    - repo: local
      hooks:
          - id: test
            name: test
            description: Runs Unit Tests
            entry: hatch run test
            language: system
            pass_filenames: false
            require_serial: false
