# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: publish

on:
    release:
        types:
            - published

jobs:
    {% if cookiecutter.publish_to_pypi == True -%}
    pypi:
        name: pypi
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/{{ cookiecutter.friendly_name }}
        permissions:
            id-token: write
        steps:
            - name: build
              uses: juftin/actions/taskfile@v1
              with:
                  checkout: true
                  setup-uv: true
                  task: dist
                  github-token: ${{"{{"}} secrets.GITHUB_TOKEN {{"}}"}}
            - name: pypi
              uses: pypa/gh-action-pypi-publish@release/v1{% endif %}
{% if cookiecutter.publish_to_docker_hub == True %}
    docker:
        name: docker
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        steps:
            - name: docker-hub
              uses: docker/login-action@v2
              with:
                  username: ${{"{{"}} secrets.DOCKER_USERNAME {{"}}"}}
                  password: ${{"{{"}} secrets.DOCKER_TOKEN {{"}}"}}
            - name: version
              run: |
                  TAG_NAME="${{"{{"}} github.event.release.tag_name {{"}}"}}"
                  RELEASE_VERSION="${TAG_NAME#v}"
                  echo "RELEASE_VERSION=${RELEASE_VERSION}"
                  echo "RELEASE_VERSION=${RELEASE_VERSION}" >> ${GITHUB_ENV}
            - name: docker
              uses: juftin/actions/taskfile@v1
              with:
                  checkout: true
                  github-token: ${{"{{"}} secrets.GITHUB_TOKEN {{"}}"}}
                  task: publish
                  buildx: true{% endif %}
