name: Release

on:
  push:
    branches:
      - main

jobs:

  release:
    name: github-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Release
        run: |
          npm install --prefix .github/semantic_release/
          npx --prefix .github/semantic_release/ semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
