# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: test

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            pull-requests: write
        steps:
            - name: test
              uses: juftin/actions/taskfile@v1
              with:
                  checkout: true
                  setup-uv: true
                  task: test
                  install: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
