name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches: ["**"]
jobs:
    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                include:
                    - { name: Python 3.12, python: "3.12" }
        concurrency:
            group: ${{ github.workflow }}-${{ matrix.python }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python Environment ${{ matrix.python }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch env create
                  hatch --version
            - name: Test Suite
              run: |
                  hatch run test
