name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches: ["**"]
jobs:
    test-suite:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python Environment
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch env create
                  hatch --version
            - name: Test Suite
              run: |
                  hatch run test
